# name: build
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# permissions:
#   contents: write # write build documentation

# jobs:
#   build-update:
#     name: build update
#     # concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#       - run: npm install
#       - run: npm run build
#       - run: git add .
#       - run: git commit -m "🤖: update build"
